name: CI-Test
on:
  pull_request:
  push:
env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  resourceGroup: ${GITHUB_SHA}
jobs:
  build:
    name: build
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: feature/APMI-1779-Automated-test-case
    
      - name: Smoke Test
        run: | 
         ./smoketest.sh 

      - name: Uploading app on sauce lab
        run: |
           cd /Users/runner/work/splunk-otel-ios/splunk-otel-ios/
           ls
           curl -u "${{secrets.SAUCE_USERNAME}}:${{secrets.SAUCE_ACCESS_KEY}}" --location \
             --request POST 'https://api.us-west-1.saucelabs.com/v1/storage/upload' \
             --form 'payload=@"SmokeTest.zip"' \
             --form 'name="SmokeTest.zip"' \
             --form 'description="'"${{ env.resourceGroup }}"'"'  
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
          
  sauce-lab:
    needs: build
    runs-on: macOS-latest
    strategy:
        fail-fast: false
        matrix:
         os: ['15.0',15.2]
         device: ['iPhone 13 Simulator','iPhone 11 Simulator']
    steps:
      - name: execute py script # run the run.py to get the latest data
        working-directory: SplunkRumWorkspace
        run: |
            cd SmokeTest/
            python3 -m pip install Appium-Python-Client
            python3 -m pip install requests
            python3 test_appium.py ${{ matrix.os }} "${{ matrix.device }}"
